### ISSUE TITLE
MessageToDict MessageToJson does not work in python 11

### ISSUE THREAD

**Issue by garawaa** [AliBigdeli/Python-Protobuf-To-JSON#1]
When I tested it under python 9 works. fine. But under python 11 it does not work. 
```
    structured_query = StructuredQuery(collection_ref.limit(50)._to_protobuf())
    structured_query_json = MessageToJson(structured_query._pb)
    structured_query_dict = MessageToDict(structured_query._pb)
```
Error message:
Traceback (most recent call last):
  File "C:\Python311\site-packages\firebase_admin\firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\site-packages\google\cloud\firestore\__init__.py", line 18, in <module>
    from google.cloud.firestore_v1 import gapic_version as package_version
  File "C:\Python311\site-packages\google\cloud\firestore_v1\__init__.py", line 26, in <module>
    from google.cloud.firestore_v1 import types
  File "C:\Python311\site-packages\google\cloud\firestore_v1\types\__init__.py", line 16, in <module>
    from .aggregation_result import (
  File "C:\Python311\site-packages\google\cloud\firestore_v1\types\aggregation_result.py", line 20, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
  File "C:\Python311\site-packages\proto\__init__.py", line 15, in <module>
    from .enums import Enum
  File "C:\Python311\site-packages\proto\enums.py", line 17, in <module>
    from google.protobuf import descriptor_pb2
  File "d:\pythondev\venv\lib\site-packages\google\protobuf\descriptor_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "d:\pythondev\venv\lib\site-packages\google\protobuf\reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "d:\pythondev\venv\lib\site-packages\google\protobuf\internal\python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "d:\pythondev\venv\lib\site-packages\google\protobuf\internal\containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by AliBigdeli** [comment]
Thanks for noticing but the problem your referring is obviously based on the version using it can be cause of changes in python new version and also keep in mind that some modules are not compatible nor tested with new incoming versions and needs to be checked before using it.
https://pypi.org/project/protobuf/#data
Based on the description protobuf module currently supports 3.10 and not 3.11.
